### ISSUE TITLE
As a user, I want to see the list of answers to a question, so I can read other peoples solutions to my problem.

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/nextjs-ask-a-dev#2]
# Show Answers
​
​
## Value proposition
**As a user**
**I want to see** the list of answers to a question,
**so that I can** read other peoples solutions to my problem
​
## Description 
[wireframe]
​
## Acceptance criteria
- when hovering over the question, it is recognizable that that each question is a Link
- clicking on the link leads to a detail page of the question
- detail page: the question is displayed
- detail page: the given answers are listed
- detail page: a Link leads back to the landing page
​
## Tasks
- [ ] create feature branch 
- [ ] use Next.js `Link` component on landing page for each question
- [ ] implement dynamic route for each question
- [ ] fetch question and answers from API with SWR
> 💡 the answers are part of the question detail request on `GET /api/questions/[id]`
- [ ] create headline with question text
- [ ] create unordered list with one list item for each answer
- [ ] use a Next.js `Link` component on detail page which leads back to landing page
​
## Complexity Estimation
M/L
