### ISSUE TITLE
As a user, I want to send in my own answers, so that I can contribute to the discussion and share knowledge.

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/nextjs-ask-a-dev#3]
# Send Answer to a Question
​
​
## Value proposition
**As a user**
**I want to see** send in my own answers,
**so that I can** contribute to the discussion and share knowledge
​
## Description 
[wireframe]
​
## Acceptance criteria
- input field for the answer is displayed on the detail page of each question
- when typing the answer, it shows how many characters are left (_optional_)
- button to send the answer
- after sending, the answer is displayed as the last entry
- a message appears, if the minimum of characters isn't reached (_optional_)
- new test (_optional_)
​
​
## Tasks
- [ ] create feature branch 
- [ ] use the `AddQuestionOrAnswer` component or feel free to build one with a `form` with `textarea` and `button` yourself.
>  💡 for usage examples, look at the tests at `components/AddQuestionOrAnswer.test.js`
- [ ] implement form functionality - add/send answer to the database (with question id and answer text)
>  💡 use the provided `sendAnswer` function in `helpers/api.js`. This function takes an `answer` string and makes the call to `POST /api/questions/[id]/answers`
- [ ] implement `AddQuestionOrAnswer` component on the question detail page
- [ ] implement form validation (e.g. required, minLength, maxLength)
- [ ] create HTML element (e.g. `<span>`) to display the left characters
- [ ] write a component test to check whether the left characters are working as expected
​
## Complexity Estimation
M/L
