### ISSUE TITLE
As a user, I want to send in my own question, so that I can ask other developers when I'm stuck in a problem or like to have further informations about a specific dev topic

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/nextjs-ask-a-dev#4]
# Send a Question
​
​
## Value proposition
**As a user**
**I want to see** send in my own question,
**so that I can** ask other developers when I'm stuck in a problem or like to have further informations about a specific dev topic
​
## Description 
[wireframe]
​
## Acceptance criteria
- input field for the question is displayed on the landing page
- when typing the answer, it shows how many characters are left (_optional_)
- button to send the answer
- after sending, the question is displayed as the last entry
- a message appears, if the minimum of characters isn't reached (_optional_)
- new test (_optional_)
​
​
## Tasks
- [ ] create feature branch 
- [ ] use the `AddQuestionOrAnswer` component or feel free to build one with a `form` with `textarea` and `button` yourself.
 (_see the user story "Send Answers"_)
- [ ] implement form functionality - add/send a new question to the database
> 💡 use the provided `sendQuestion` function in `helpers/api.js`. This function takes a `question` string and makes the call to `POST /api/questions`
- [ ] implement form validation (e.g. `required`, `minLength`, `maxLength`)  (_see user story "Send Answer"_)
- [ ] create HTML element (e.g. `<span>`) to display the left characters  (_see user story "Send Answer"_)
- [ ] write a component test to check whether the left characters are working as expected
​
## Complexity Estimation
M
